csusmGDSC/csusmgdsc-api

.gitignore
config/config.go
go.mod
go.sum
internal/auth/auth_handler.go
internal/auth/jwt.go
internal/auth/oauth.go
internal/db/repositories/user_repo.go
internal/handlers/user_handler.go
internal/models/gdsc_branch.go
internal/models/gdsc_position.go
internal/models/user.go
routes/routes.go

These changes are enough to setup our project to start structuring our development workflow.
These changes introduce our file structure, route management, and SQL handling.

Setup Project Structure and Authentication

---

internal/db/repositories/user_repo.go
internal/handlers/user_handler.go
routes/routes.go

Builds on PR #6 
Allows for users to be deleted.

feat: Add User route for deletion

---

cmd/main.go
config/config.go
internal/db/connection.go
internal/handlers/event_handler.go
internal/handlers/handler.go
internal/handlers/user_handler.go
routes/routes.go

As noted in #8 further refactoring is done to modularize the codebase for better testability.  The configuration and database connect logic was repeated throughout the application before, now concurrency is being used.  Config is loaded once and db is connected to once and they're used about the application.
This change is inspired by unit test development, which will be coming in the next PR.

Refactor: Config, DB, and Handlers to Layered Architecture with Dependency Injection

---

config/config.go
internal/auth/auth_handler.go
internal/auth/jwt.go
internal/handlers/user_handler.go

Closes #17
Removes old config functions and replaces their use to updated config singleton pattern.

Update Codebase to Singleton ConfigLoad

---

.env.test
cmd/main.go
config/config.go
internal/auth/auth_handler.go
internal/auth/jwt.go
internal/auth/oauth.go
internal/models/user.go
routes/routes.go

Implements OAuth2 with Github + Google Closes #13

feat: Add OAuth2 providers: Github, Google

---

.gitignore
Dockerfile

Closes #22 and Closes #23 
Application is containerized and EC2 instance is setup to reflect latest docker container.  Next is to setup CI/CD using GitHub actions to containerize and push default branch code.

feat: Add docker containerization for hosting backend api

---

internal/db/repositories/event_repo.go
internal/models/event.go

Event handler and model updated to handle physical meeting creation.

feat: Update event handler and model

---

internal/auth/auth_handlers/auth_handler.go
internal/auth/auth_models/user.go
internal/auth/auth_repositories/user_repo.go
internal/handlers/event_handler.go
internal/handlers/user_handler.go
routes/routes.go

This Closes #33
Implements routes for getting users, by id and all users with pagination.
Additionally event creation was set under an admin route group and uses auth middleware to verify permissions.

User Getters!

---

internal/db/repositories/event_repo.go
internal/handlers/event_handler.go
internal/models/event.go
routes/routes.go

Similar to User Getters #35 this PR implements getter routes for events, get from all events with pagination, and get event by id.
/events?page=x&limit=y
/events/:id
Closes #36

Add GET Routes for Events

---

.github/workflows/docker-publish.yml

Use Github docs to refactor action file.

bug: Update CD action

---

.github/workflows/docker-publish.yml

update: run action on main not release

---

internal/auth/auth_models/user.go
internal/auth/auth_repositories/user_repo.go

Closes #40 
Add IsOnboarded field to UpdateUser handler.

feat: Update UpdateUser Handler to allow for updating is_onboarded

---

internal/auth/auth_handlers/auth_handler.go
internal/auth/auth_utils/oauth.go
internal/auth/auth_utils/traditional_auth.go

The session code has been refactored by:
1- moving the session code from auth_handler/LoginUser and auth_handler/OAuthCallback to oauth.go
2- adding the appropriate errors in auth_utils/triditional_auth which is used in CreateLoginSession
3- removing the refactored code from the tow function above

Refactor code

---

internal/auth/auth_handlers/auth_handler.go
internal/auth/auth_utils/oauth.go
internal/auth/auth_utils/traditional_auth.go

Merging PR #45 changes to dev branch

Propagate Refactor Code to Working Branch

---

README.md

Adding link to DBeaver for db visualization, and more details on making changes.

Update ReadMe More Info for New Contributors

---

config/config.go
internal/auth/auth_handlers/auth_handler.go
internal/auth/auth_models/user.go
internal/auth/auth_repositories/user_repo.go
internal/handlers/user_handler.go
internal/models/user.go

This PR Closes #48 
GetAll repo function scan logic updated to pull all relevant user information.
Update repo function updated to be build query based on req data, position and branch were being ignored previously.  Use query builder structure for SQL injection safety.
Config removed OAuthRedirectUrl, no longer needed.

Users Routes Return Accurate Information

---

.github/workflows/assign-db-access.yml
.github/workflows/revoke-db-access.yml

Adds workflow to create role for connecting to test-branch on neon upon assignment of an issue.
Adds workflow to remove temporary role upon issue being closed.

Add Workflows for Generating Neon Credentials

---

.github/workflows/assign-db-access.yml
.github/workflows/revoke-db-access.yml

CI connection string updated to test-branch

Update CI Neon DB Connection String

---

.github/workflows/assign-db-access.yml
.github/workflows/revoke-db-access.yml

Special characters such as '-' need to be quoted for sql command to interpret.  Additionally, trigger role revoke on issue close or pr close instead of just pr close.

Update CI Neon Workflow, Handle Special Characters

---

.github/workflows/assign-db-access.yml
.github/workflows/revoke-db-access.yml

Closes #71 
The issue was permissions related to the refresh_tokens_id_seq, Stack Overflow [fix](https://stackoverflow.com/questions/9325017/error-permission-denied-for-sequence-cities-id-seq-using-postgres)

fix: add permissions for refresh_tokens_id_seq for dev users

---

config/config.go
go.mod
go.sum
internal/auth/auth_handlers/auth_handler.go
internal/auth/auth_repositories/refresh_tokens.go
internal/auth/auth_repositories/user_repo.go
internal/auth/auth_utils/jwt.go
internal/auth/auth_utils/oauth.go
internal/auth/auth_utils/traditional_auth.go
routes/routes.go

Added functionality: 
- New registered user receives email to verify. 
- Unverified user will receive a verification email upon logging in. 
- After user clicks on verification button in email verify rout is triggered and sets user as verified in db .
Changes:
- Added SendVerificationEmail function with parameters (userid, token).
- Updated auth_repositories to accommodate the email_verified field.
-  Register route calls sendVerificationEmail function.
- Login route checks if user verified or not then calls sendVerificationEmail accordingly.
**Issues:**
- Not sure why, but emails doesn't get send to school emails when using personal domain. I tried Resend domain and it works but when trying my personal email I receive nothing. issue might be related to Domain.
**Changes needs to be …

Email Verification 

---

config/config.go
go.mod
go.sum
internal/db/repositories/event_organizer_repo.go
internal/db/repositories/event_repo.go
internal/db/repositories/utils_repo.go
internal/handlers/event_handler.go
internal/handlers/event_organizer_handler.go
internal/handlers/utils_handler.go
internal/models/event.go
routes/routes.go

Event API Update
